In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/KEERTHI/Downloads/all_tickets.csv")
df.head()

,id,subject,body,answer,type,queue,priority,language,business_type,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8,tag_9
0,1001352387736,Urgent: Critical impact on enterprise network ...,"Dear Customer Support Team, We are experiencin...",Subject: Re: Urgent: Critical impact on enterp...,Incident,Technical Support,high,en,IT Services,Service Outage,Network Issue,Urgent Issue,Technical Support,Problem Resolution,Critical Failure,System Crash,Service Disruption,NaN
1,1004699418379,Intermittent Cursor Freezing Issue on Dell XPS,"Dear Customer Support,<br><br>I hope this mess...","Dear <name>,\n\nThank you for reaching out reg...",Incident,Product Support,low,en,Tech Online Store,Technical Support,Product Support,Hardware Failure,Problem Resolution,Urgent Issue,Service Recovery,Documentation Request,NaN,NaN
2,1006966905046,Dringend: Unterstützung für die Datenwiederher...,"Hallo, wir haben severe Datenverluste in MySQL...","Hallo, vielen Dank, dass Sie uns kontaktiert h...",Incident,Technical Support,high,de,IT Services,Data Breach,Backup Restore,Technical Support,Urgent Issue,Software Bug,Problem Resolution,NaN,NaN,NaN
3,1009231330404,Anfrage zu den MacBook Air M1 Funktionen,"Sehr geehrtes Kundenserviceteam,\n\nich hoffe,...","Sehr geehrter <name>,\n\nvielen Dank für Ihre ...",Request,Sales and Pre-Sales,low,de,Tech Online Store,Customer Service,Product Support,Sales Inquiry,Technical Guidance,Warranty Claim,General Inquiry,NaN,NaN,NaN
4,1024440081041,Solicitação de Assistência com Erro de Instala...,"Caro Suporte ao Cliente,\n\nEstou enfrentando ...","Caro <name>,\n\nObrigado por entrar em contato...",Problem,Technical Support,medium,pt,IT Services,Technical Support,Software Bug,Urgent Issue,Problem Resolution,Product Support,NaN,NaN,NaN,NaN

In [4]:
df.shape

(1566, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1566 non-null   int64
 1   subject        1565 non-null   object
 2   body           1565 non-null   object
 3   answer         1566 non-null   object
 4   type           1566 non-null   object
 5   queue          1566 non-null   object
 6   priority       1566 non-null   object
 7   language       1566 non-null   object
 8   business_type  1566 non-null   object
 9   tag_1          1566 non-null   object
 10  tag_2          1566 non-null   object
 11  tag_3          1566 non-null   object
 12  tag_4          1566 non-null   object
 13  tag_5          1419 non-null   object
 14  tag_6          1011 non-null   object
 15  tag_7          489 non-null    object
 16  tag_8          137 non-null    object
 17  tag_9          0 non-null      float64
dtypes: float64(1), int64(1), object(16)
memory usage: 220.3+ KB

In [8]:
df.describe(include='all')

,id,subject,body,answer,type,queue,priority,language,business_type,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8,tag_9
count,1.566000e+03,1565,1565,1566,1566,1566,1566,1566,1566,1566,1566,1566,1566,1419,1011,489,137,0.0
unique,NaN,1565,1565,1566,4,10,3,5,5,25,38,54,63,62,56,42,31,NaN
top,NaN,Urgent: Critical impact on enterprise network ...,"Dear Customer Support Team, We are experiencin...",Subject: Re: Urgent: Critical impact on enterp...,Incident,Technical Support,high,de,IT Services,Technical Support,Product Support,Urgent Issue,Problem Resolution,Problem Resolution,Problem Resolution,Problem Resolution,Service Recovery,NaN
freq,NaN,1,1,1,663,589,788,397,748,756,329,198,391,329,209,64,29,NaN
mean,4.801366e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.627746e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.001352e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.506892e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.351363e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.014945e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,9.998325e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.isnull().sum()

id                  0
subject             1
body                1
answer              0
type                0
queue               0
priority            0
language            0
business_type       0
tag_1               0
tag_2               0
tag_3               0
tag_4               0
tag_5             147
tag_6             555
tag_7            1077
tag_8            1429
tag_9            1566
dtype: int64

In [12]:
df.nunique()

id               1566
subject          1565
body             1565
answer           1566
type                4
queue              10
priority            3
language            5
business_type       5
tag_1              25
tag_2              38
tag_3              54
tag_4              63
tag_5              62
tag_6              56
tag_7              42
tag_8              31
tag_9               0
dtype: int64

In [14]:
df['priority'].value_counts()

priority
high      788
medium    572
low       206
Name: count, dtype: int64

In [16]:
df.groupby('priority')['type'].value_counts()

priority  type
high      Incident    378
          Request     181
          Problem     158
          Change       71
low       Request      92
          Incident     57
          Problem      33
          Change       24
medium    Incident    228
          Request     195
          Problem     101
          Change       48
Name: count, dtype: int64

In [18]:
df.columns[df.isnull().all()]
df.columns[df.isnull().mean() > 0.5]

Index(['tag_7', 'tag_8', 'tag_9'], dtype='object')

In [20]:
df = df.drop(columns=['tag_9'])

In [22]:
df = df.fillna('Unknown')

In [26]:
df['subject'].value_counts().head(10)

subject
Urgent: Critical impact on enterprise network connectivity                        1
Urgente: Se requiere resolución inmediata para el tiempo de inactividad de AWS    1
Problemas de conectividad intermitente en ISR4331                                 1
Abrechnungsdifferenz                                                              1
Solicitud de intercambio de impresora                                             1
Problemas de Faturamento nos Serviços AWS                                         1
Urgente: Serviço de Gerenciamento AWS Fora do Ar                                  1
Problema Urgente com Macro do Excel                                               1
Problema con Surface Pro 7 - Pantalla parpadeante                                 1
Soforthilfe erforderlich                                                          1
Name: count, dtype: int64

In [28]:
tags_columns = ['tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8']
all_tags = df[tags_columns].apply(lambda x: ','.join(x.dropna()), axis=1)
all_tags_series = all_tags.str.split(',').explode()
most_common_tags = all_tags_series.value_counts().head(10)
most_common_tags

Unknown               3208
Technical Support     1289
Problem Resolution    1126
Urgent Issue           842
Product Support        606
IT Support             530
Service Disruption     463
Technical Guidance     423
Software Bug           361
Customer Service       358
Name: count, dtype: int64

In [30]:
high_priority_issues = df[df['priority'] == 'high']
high_priority_issues['subject'].value_counts().head(10)

subject
Urgent: Critical impact on enterprise network connectivity                        1
Urgente: Se requiere resolución inmediata para el tiempo de inactividad de AWS    1
Unmittelbare Hilfe für den Zugriff auf AWS erforderlich                           1
Soforthilfe erforderlich                                                          1
Problema con Surface Pro 7 - Pantalla parpadeante                                 1
Problema Urgente com Macro do Excel                                               1
Urgente: Serviço de Gerenciamento AWS Fora do Ar                                  1
Problemas de Faturamento nos Serviços AWS                                         1
Urgent : Ordinateur portable Dell XPS 13 9310 ne s'allume pas                     1
Unterstützung bei Adobe Photoshop                                                 1
Name: count, dtype: int64

In [32]:
df.groupby('type').size().sort_values(ascending=False)

type
Incident    663
Request     468
Problem     292
Change      143
dtype: int64

In [34]:
df.groupby(['type', 'queue', 'priority']).size().sort_values(ascending=False).head(10)

type      queue              priority
Incident  Technical Support  high        218
Problem   Technical Support  high         79
Request   Technical Support  high         72
          Customer Service   medium       66
Incident  Technical Support  medium       66
          Product Support    high         54
Problem   Technical Support  medium       53
Incident  IT Support         high         49
          Product Support    medium       47
          Customer Service   medium       37
dtype: int64